# Generated by Django 5.2.5 on 2025-08-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_orders', models.IntegerField(blank=True, default=0, null=True)),
                ('sum_of_orders', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'all_users',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.IntegerField()),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_allsneaker', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Заказ поступил', 'Заказ поступил'), ('Сборка заказа', 'Сборка заказа'), ('Заказ отправлен', 'Заказ отправлен'), ('Завершён', 'Завершён')], default='Заказ поступил', max_length=255)),
            ],
            options={
                'db_table': 'active_orders',
            },
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('count_of_sneakers', models.IntegerField(blank=True, default=0, null=True)),
                ('sum_sneakers', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'sneaker',
            },
        ),
    ]
